### ISSUE TITLE
Activating extension Docker.docker failed due to an error

### ISSUE THREAD

**Issue by doggy8088** [docker/docker-ai#4]
Here is the log I found on Extension Host in the OUTPUT pane.

```log
2024-03-01 01:24:08.449 [info] ExtensionService#_doActivateExtension Docker.docker, startup: false, activationEvent: 'workspaceContains:*'
2024-03-01 01:24:09.073 [error] Activating extension Docker.docker failed due to an error:
2024-03-01 01:24:09.073 [error] TypeError: Cannot read properties of undefined (reading 'slice')
	at c:\Users\user\.vscode\extensions\docker.docker-0.0.5-pre\dist\extension.bundle.js:1:98803
	at Generator.next (<anonymous>)
	at c:\Users\user\.vscode\extensions\docker.docker-0.0.5-pre\dist\extension.bundle.js:1:97133
	at new Promise (<anonymous>)
	at a (c:\Users\user\.vscode\extensions\docker.docker-0.0.5-pre\dist\extension.bundle.js:1:96819)
	at t.preflights (c:\Users\user\.vscode\extensions\docker.docker-0.0.5-pre\dist\extension.bundle.js:1:98496)
	at Object.<anonymous> (c:\Users\user\.vscode\extensions\docker.docker-0.0.5-pre\dist\extension.bundle.js:1:92587)
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\user\.vscode\extensions\docker.docker-0.0.5-pre\dist\extension.bundle.js:1:90321)
```

```sh
# docker system df --format json
```

```log
{"Active":"0","Reclaimable":"38.02GB (100%)","Size":"38.02GB","TotalCount":"26","Type":"Images"}
{"Active":"0","Reclaimable":"0B","Size":"0B","TotalCount":"0","Type":"Containers"}
{"Active":"0","Reclaimable":"7.054GB (100%)","Size":"7.054GB","TotalCount":"2","Type":"Local Volumes"}
{"Active":"0","Reclaimable":"455.7MB","Size":"455.7MB","TotalCount":"113","Type":"Build Cache"}
```

In Line 2 (`"Type":"Containers"`), the `Reclaimable` is `0B` which is not consistent with others. That probably cause the issue. At this moment, I don't have any running container.

**Comment by ColinMcNeil** [comment]
Closed as this feature has been removed.
